server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    pessoa:
      service-id: ms-pessoa
      path: /ms-pessoa/**

    folha-pagamento:
      service-id: ms-folha-pagamento
      path: /ms-folha-pagamento/**

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/studyapplication #keycloak

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 20000